# See https://pre-commit.com/#usage
repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: end-of-file-fixer
    exclude: "internal/parser/(.*.(tokens|inter)|zserio.*.go)"
  - id: check-merge-conflict
  #- id: trailing-whitespace
  #- id: requirements-txt-fixer
- repo: https://github.com/keith/pre-commit-buildifier
  rev: 6.4.0.1
  hooks:
    - id: buildifier
    - id: buildifier-lint
- repo: local
  hooks:
    - id: module-bazel-lock
      name: Ensure that the MODULE.bazel.lock is up-to-date
      entry: bazel mod deps --lockfile_mode=update
      language: system
      files: '^(MODULE.bazel|.bazelversion)$'
      pass_filenames: false
