# See https://pre-commit.com/#usage
repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.7
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: end-of-file-fixer
    exclude: "internal/parser/(.*.(tokens|inter)|zserio.*.go)"
  #- id: trailing-whitespace
  #- id: requirements-txt-fixer
- repo: local
  hooks:
    - id: buildifier
      name: buildifier
      language: system
      entry: bazel run -- //:buildifier --mode=fix --lint=warn --warnings=all
      types: [file]
      files: /(BUILD.bazel|WORKSPACE|.*\.bzl)$
