name: Run tests

on: push

jobs:
  lint:
    name: Run linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Check for uncommited changes
        run: |
          ./bin/ensure-unchanged bazel run //:buildifier
          ./bin/ensure-unchanged ./bin/gazelle
          ./bin/ensure-unchanged ./bin/gazelle-update-repos

  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    name: Run tests on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel

      - run: bazel test //...

  integration_test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    name: Test example on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '1.18.0-beta2'

      - run: ./bin/ensure-unchanged ./example/test.sh
